# Generated by Django 4.0.5 on 2022-06-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('hecho', models.BooleanField()),
            ],
        ),
    ]
